export const DEMO_WITHDRAWAL_NAMES: string[] = [
  // United Kingdom (UK)
  "Oliver Bennett",
  "Amelia Clarke",
  "Harry Thompson",
  "Isla Morgan",
  "Jack Wilson",
  "Sophia Carter",
  "Noah Edwards",
  "Emily Harrison",

  // United States
  "James Miller",
  "Ava Johnson",
  "Ethan Davis",
  "Mia Brown",
  "Benjamin Anderson",
  "Charlotte Martinez",
  "Daniel Taylor",
  "Harper Moore",

  // India
  "Arjun Mehta",
  "Ananya Iyer",
  "Rohan Sharma",
  "Priya Nair",
  "Karan Gupta",
  "Neha Kapoor",
  "Vikram Singh",
  "Ishita Patel",

  // Spain
  "Alejandro García",
  "Lucía Fernández",
  "Mateo Rodríguez",
  "Sofía López",
  "Hugo Martínez",
  "Valeria Sánchez",
  "Daniel Pérez",
  "Carmen González",

  // Italy
  "Lorenzo Rossi",
  "Giulia Bianchi",
  "Matteo Conti",
  "Francesca Romano",
  "Andrea Esposito",
  "Chiara Ricci",
  "Marco De Luca",
  "Sara Greco",

  // South Africa
  "Thabo Nkosi",
  "Nomsa Dlamini",
  "Sipho Mokoena",
  "Lerato Khumalo",
  "Mandla Naidoo",
  "Zanele Botha",
  "Kagiso van Wyk",
  "Ayesha Jacobs",
];

export const DEMO_COUNTRIES: string[] = [
  "United Kingdom",
  "United States",
  "India",
  "Spain",
  "Italy",
  "South Africa",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Netherlands",
  "Sweden",
  "Norway",
  "Denmark",
  "Switzerland",
  "Ireland",
  "Portugal",
  "Belgium",
  "Austria",
  "Poland",
  "Czech Republic",
  "Greece",
  "Finland",
  "New Zealand",
  "Singapore",
  "Japan",
  "South Korea",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Turkey",
  "Israel",
  "Brazil",
  "Mexico",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "Nigeria",
  "Ghana",
  "Kenya",
  "Egypt",
  "Morocco",
  "Tunisia",
  "Philippines",
  "Malaysia",
  "Indonesia",
  "Thailand",
  "Vietnam",
  "Hong Kong",
];
